### PR TITLE
Update to version 4.6.1

### PR DESCRIPTION
**Pull request by aryasenna**
Bump version to 4.6.0.

### CODE REVIEW

**Comment by aryasenna** [comment]
Hi @bilelmoussaoui :) Any chance you can review this PR? Thanks.

**Comment by bilelmoussaoui** [comment]
Thanks!

**Comment by aryasenna** [comment]
@bilelmoussaoui  Oh no, I forget to update version in the com.flashforge.FlashPrint.metainfo.xml  to 4.6.1. Sorry!
 
What  would be your recommendation? I make another pull request?

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui  Oh no, I forget to update version in the com.flashforge.FlashPrint.metainfo.xml  to 4.6.1. Sorry!
>  
> What  would be your recommendation? I make another pull request?
> 
> 

Yes please :)

**Comment by aryasenna** [comment]
> > @bilelmoussaoui  Oh no, I forget to update version in the com.flashforge.FlashPrint.metainfo.xml  to 4.6.1. Sorry!
> > What  would be your recommendation? I make another pull request?
> 
> Yes please :)

Sure thing, the fix is here: https://github.com/flathub/com.flashforge.FlashPrint/pull/12

**Pull request merged**
