### PR TITLE
update to 4.2

### PR DESCRIPTION
**Pull request by artemisart**

### CODE REVIEW

**Comment by danilos2k** [comment]
Hello! 
do you think will be possible to update to the new version ? thank you very much in advance :-)

**Comment by artemisart** [comment]
Sorry no, my last update got ignored for 4 months and I never managed to build it locally or install the testing repository so I'm unable to test it.

**Comment by danilos2k** [comment]
> Sorry no, my last update got ignored for 4 months and I never managed to build it locally or install the testing repository so I'm unable to test it.

ok thank you for your reply, there is not another solution to update the app? i'm not a linux espert.... thank you, Danilo

**Comment by bilelmoussaoui** [comment]
Updated

**Pull request closed without merging**
